#!/bin/bash

function usage()
{
    printf "Usage: $(basename $0) [-g groupname]\n"
    printf "%-4s%-14s%-48s\n"  "-i" "file name" "Input file name"
    printf "%-4s%-14s%-48s\n"  "-o" "file name" "Output file name"
    printf "%-4s%-14s%-48s\n"  "-h"          "" "Print all of this"
}

# Get the input file name and the box size
while getopts "i:o:h" opt
do
    case ${opt} in
        i)
            # Input file name argument to -i
            ifn="${OPTARG}"
            ;;
        o)
            # Output file name argument to -o
            ofn="${OPTARG}"
            ;;
        h)
            # Call usage() because user screwed up and
            # needs to be educated on her/his failures
            usage
            exit 127
            ;;
        *)
            printf "Bad option given\n"
            exit 126
            ;;
    esac
done

# Exactly three (3) coordinates must be found separated by 
inp="$(sed -nr -e '/^[0-9]+(\.[0-9]+)?(,[0-9]+(\.[0-9]+)?){2}$/p' <<<"${1}")"
if [ -n "${inp}" ]; then
    box="$(sed -r -e 's/,/ /g' <<<${inp})"
fi

echo ${inp}
echo ${box}

exit 0

awk '(NF==3)&&($1~/[0-9]+\.[0-9]+/){
        rep = gensub(/([^0-9\.]*)[0-9]+\.[0-9]+([^0-9\.]*)/,"\\16.89520\\2","g",$0);
        print rep;
        next;
     }
     {
        print $0;
     }' confout.gro >confout-box.gro

# vim: tabstop=4:softtabstop=4:shiftwidth=4:expandtab:smarttab
