#!/bin/bash

Tr_inp=${Tr:-1.0}           # Units: unitless (reduced T)
m_inp=${m:-0.039948}        # Units: kg/mol
sig_inp=${sig:-0.3401}      # Units: nm
eps_inp=${eps:-0.978638}    # Units: kJ/mol

octave --silent <<eof
Trx   = ${Tr_inp};      # unitless (reduced T)
m = ${m_inp};           # kg (per atom)
sigAA = ${sig_inp};     # nm
epsAA = ${eps_inp};     # kJ/mol
[dt,dt2,T,ro,s1,e1,s2,e2,s3,e3] = kobandprms(m,sigAA,epsAA,Trx)
eof

